export const GET_TOP_ARTISTS = 'GET_TOP_ARTISTS';
export const GET_TOP_TRACKS = 'GET_TOP_TRAKS';
export const GET_NEXT_TOP_ARTIST = 'GET_NEXT_TOP_ARTIST';
export const GET_PREV_TOP_ARTIST = 'GET_PREV_TOP_ARTIST';
export const GET_NEXT_TOP_TRACK = 'GET_NEXT_TOP_TRACK';